module.exports = {
  meals: [
    {
      img: "meal_1.jpg",
      title: "Beef shabu-shabu",
      included: "with noodle and rice",
      desc:
        "Japanese nabemono hotpot dish of thinly sliced meat and vegetables boiled in water",
      category: "asia",
      serving: 2,
      calroriesPerServing: 600,
      isAsia: true,
      topmeal: true,
      cookingTime: 20,
      price: "$20.00",
    },
    {
      img: "meal_2.jpg",
      title: "Cream pasta with garlic",
      included: "with ricota cheese salad",
      price: "$12.00",
      desc: "Home-made cream pasta sauce with garlic.",
      category: "western",
      isWestern: true,
      serving: 1,
      calroriesPerServing: 550,
      topmeal: true,
      cookingTime: 15,
    },
    {
      img: "meal_4.jpg",
      title: "Yaki soba",
      included: "with dumplings",
      price: "$12.00",
      desc: "Stir-fry noodle with soy sauce",
      category: "asia",
      isAsia: true,
      serving: 1,
      calroriesPerServing: 440,
      topmeal: false,
      cookingTime: 15,
    },
    {
      img: "meal_3.jpg",
      title: "Spicy cold noodle",
      included: "with dumplings",
      price: "$15.00",
      desc: "Cold noodle with Korean spicy sauce",
      category: "asia",
      isAsia: true,
      serving: 2,
      calroriesPerServing: 440,
      topmeal: true,
      cookingTime: 10,
    },
    {
      img: "meal_5.jpg",
      title: "Korean army soup",
      included: "with two bowls of rice",
      price: "$23.00",
      desc: "Soup with a lot of sausages and ham",
      category: "asia",
      isAsia: true,
      serving: 2,
      calroriesPerServing: 640,
      topmeal: false,
      cookingTime: 25,
    },
    {
      img: "meal_6.jpg",
      title: "Mac and cheese",
      included: "with nacho chips",
      price: "$8.00",
      desc: "Dish of cooked macaroni pasta and a cheese sauce",
      category: "western",
      isWestern: true,
      serving: 2,
      calroriesPerServing: 500,
      topmeal: false,
      cookingTime: 15,
    },
    {
      img: "meal_7.jpg",
      title: "Quatro cheese pasta",
      included: "with breads and salad",
      price: "$18.00",
      desc: "Cream sauce pasta in the bread",
      category: "western",
      isWestern: true,
      serving: 2,
      calroriesPerServing: 700,
      topmeal: false,
      cookingTime: 20,
    },
    {
      img: "meal_8.jpg",
      title: "Black label steak set",
      included: "with vegetables",
      price: "$30.00",
      desc: "AAA+ sirloin beef with assorted vegetables",
      category: "western",
      isWestern: true,
      serving: 2,
      calroriesPerServing: 600,
      topmeal: false,
      cookingTime: 15,
    },
  ],
};
